// AUTO-GENERATED by scripts/audit-assets.mjs — do not edit by hand.
// Real measured dimensions (world units), pivot, and texture presence for
// every .glb in /models. Placement, scaling, and fencing read from here so
// nothing is a guessed constant (Prompt 04b, step 1).

export type Pivot = "base" | "center";

export interface AssetEntry {
  /** Path relative to the repo root (matches the ?url import in models.ts). */
  readonly path: string;
  /** Real bounding-box size in the model's own units. */
  readonly dimensions: { readonly width: number; readonly height: number; readonly depth: number };
  /** "base" = origin at the foot (y=0 sits on the ground); "center" = mid-height. */
  readonly pivot: Pivot;
  /** Whether the model carries a color texture (Kenney colormap atlas). */
  readonly textured: boolean;
  /** Measured min.y in model space (grounding offset reference). */
  readonly baseY: number;
}

export const ASSET_MANIFEST = {
  "fence_1x4": {"path":"/models/fences/fence-1x4.glb","dimensions":{"width":1.675,"height":0.27,"depth":0.438},"pivot":"base","textured":true,"baseY":0},
  "fence_2x2": {"path":"/models/fences/fence-2x2.glb","dimensions":{"width":0.875,"height":0.27,"depth":0.837},"pivot":"base","textured":true,"baseY":0},
  "fence_2x3": {"path":"/models/fences/fence-2x3.glb","dimensions":{"width":1.275,"height":0.27,"depth":0.837},"pivot":"base","textured":true,"baseY":0},
  "fence_3x2": {"path":"/models/fences/fence-3x2.glb","dimensions":{"width":0.875,"height":0.27,"depth":1.238},"pivot":"base","textured":true,"baseY":0},
  "fence_3x3": {"path":"/models/fences/fence-3x3.glb","dimensions":{"width":1.275,"height":0.27,"depth":1.238},"pivot":"base","textured":true,"baseY":0},
  "building_type_a": {"path":"/models/houses/building-type-a.glb","dimensions":{"width":1.3,"height":0.834,"depth":1.028},"pivot":"base","textured":true,"baseY":0},
  "building_type_b": {"path":"/models/houses/building-type-b.glb","dimensions":{"width":1.828,"height":1.138,"depth":1.14},"pivot":"base","textured":true,"baseY":0},
  "building_type_c": {"path":"/models/houses/building-type-c.glb","dimensions":{"width":1.286,"height":1.034,"depth":1.028},"pivot":"base","textured":true,"baseY":0},
  "building_type_d": {"path":"/models/houses/building-type-d.glb","dimensions":{"width":1.756,"height":1.238,"depth":1.028},"pivot":"base","textured":true,"baseY":0},
  "building_type_e": {"path":"/models/houses/building-type-e.glb","dimensions":{"width":1.3,"height":1.138,"depth":1.028},"pivot":"base","textured":true,"baseY":0},
  "building_type_f": {"path":"/models/houses/building-type-f.glb","dimensions":{"width":1.428,"height":1.138,"depth":1.406},"pivot":"base","textured":true,"baseY":0},
  "building_type_g": {"path":"/models/houses/building-type-g.glb","dimensions":{"width":1.45,"height":0.768,"depth":1.178},"pivot":"base","textured":true,"baseY":0},
  "building_type_h": {"path":"/models/houses/building-type-h.glb","dimensions":{"width":1.3,"height":0.737,"depth":0.916},"pivot":"base","textured":true,"baseY":0},
  "building_type_i": {"path":"/models/houses/building-type-i.glb","dimensions":{"width":1.286,"height":0.737,"depth":1.028},"pivot":"base","textured":true,"baseY":0},
  "building_type_j": {"path":"/models/houses/building-type-j.glb","dimensions":{"width":1.37,"height":1.038,"depth":0.916},"pivot":"base","textured":true,"baseY":0},
  "building_type_k": {"path":"/models/houses/building-type-k.glb","dimensions":{"width":0.921,"height":1.15,"depth":1.02},"pivot":"base","textured":true,"baseY":0},
  "building_type_l": {"path":"/models/houses/building-type-l.glb","dimensions":{"width":1.034,"height":1.049,"depth":1.02},"pivot":"base","textured":true,"baseY":0},
  "path_long": {"path":"/models/path/path-long.glb","dimensions":{"width":0.2,"height":0.01,"depth":0.4},"pivot":"base","textured":true,"baseY":0},
  "path_short": {"path":"/models/path/path-short.glb","dimensions":{"width":0.2,"height":0.01,"depth":0.2},"pivot":"base","textured":true,"baseY":0},
  "path_stones_long": {"path":"/models/path/path-stones-long.glb","dimensions":{"width":0.14,"height":0.01,"depth":0.4},"pivot":"base","textured":true,"baseY":0},
  "path_stones_messy": {"path":"/models/path/path-stones-messy.glb","dimensions":{"width":0.156,"height":0.01,"depth":0.361},"pivot":"base","textured":true,"baseY":0},
  "path_stones_short": {"path":"/models/path/path-stones-short.glb","dimensions":{"width":0.14,"height":0.01,"depth":0.2},"pivot":"base","textured":true,"baseY":0},
  "planter": {"path":"/models/path/planter.glb","dimensions":{"width":0.4,"height":0.177,"depth":0.3},"pivot":"base","textured":true,"baseY":0},
} as const satisfies Record<string, AssetEntry>;

export type AssetKey = keyof typeof ASSET_MANIFEST;
